export type Restaurant = {
  id: string;
  name: string;
  type: string;
  image: any;
  route: string;
  latitude: number;
  longitude: number;
  rating: number;
  price: number;
  hours: string[];
  dietTypes: string[];
  allergySafe: string[];
  allergyRisk: string[];
  healthGoals: string[];
};

export const ALL_RESTAURANTS: Restaurant[] = [
  {
    id: "1",
    name: "Chick-Fil-A",
    type: "American fast food",
    image: require("../assets/images/chickfila.jpg"),
    route: "/restaurantprof_chickfila",
    latitude: 28.5960,
    longitude: -81.1988,
    rating: 3.7,
    price: 1,
    hours: [
      "Monday: 7:30 AM – 8:00 PM",
      "Tuesday: 7:30 AM – 8:00 PM",
      "Wednesday: 7:30 AM – 8:00 PM",
      "Thursday: 7:30 AM – 8:00 PM",
      "Friday: 7:30 AM – 5:00 PM",
      "Saturday: 11:00 AM – 4:00 PM",
      "Sunday: Closed",
    ],
    dietTypes: ["omnivore", "vegetarian"],
    allergySafe: [],
    allergyRisk: ["gluten", "dairy", "eggs"],
    healthGoals: ["manageweight"],
  },
  {
    id: "2",
    name: "Qdoba",
    type: "Mexican food",
    image: require("../assets/images/qdoba.jpg"),
    route: "/restaurantprof_qdoba",
    latitude: 28.5480,
    longitude: -81.3876,
    rating: 3.9,
    price: 1,
    hours: [
      "Monday: 10:30 AM – 9:00 PM",
      "Tuesday: 10:30 AM – 9:00 PM",
      "Wednesday: 10:30 AM – 9:00 PM",
      "Thursday: 10:30 AM – 9:00 PM",
      "Friday: 10:30 AM – 9:00 PM",
      "Saturday: 10:30 AM – 9:00 PM",
      "Sunday: 11:00 AM – 8:00 PM",
    ],
    dietTypes: ["omnivore", "vegetarian", "vegan"],
    allergySafe: [],
    allergyRisk: ["gluten", "dairy"],
    healthGoals: ["manageweight"],
  },
  {
    id: "3",
    name: "Huey Magoos",
    type: "American fast food",
    image: require("../assets/images/huey.jpg"),
    route: "/restaurantprof_huey",
    latitude: 28.6125,
    longitude: -81.2084,
    rating: 3.2,
    price: 1,
    hours: [
      "Monday: 10:30 AM – 11:00 PM",
      "Tuesday: 10:30 AM – 11:00 PM",
      "Wednesday: 10:30 AM – 11:00 PM",
      "Thursday: 10:30 AM – 11:00 PM",
      "Friday: 10:30 AM – 11:00 PM",
      "Saturday: 10:30 AM – 11:00 PM",
      "Sunday: 10:30 AM – 11:00 PM",
    ],
    dietTypes: ["omnivore"],
    allergySafe: [],
    allergyRisk: ["gluten"],
    healthGoals: ["manageweight"],
  },
  {
    id: "4",
    name: "Panda Express",
    type: "Chinese fast food",
    image: require("../assets/images/panda.jpeg"),
    route: "/restaurantprof_panda",
    latitude: 28.6022,
    longitude: -81.2004,
    rating: 4.0,
    price: 1,
    hours: [
      "Monday: 11:00 AM – 8:00 PM",
      "Tuesday: 11:00 AM – 8:00 PM",
      "Wednesday: 11:00 AM – 8:00 PM",
      "Thursday: 11:00 AM – 8:00 PM",
      "Friday: 11:00 AM – 6:00 PM",
      "Saturday: Closed",
      "Sunday: Closed",
    ],
    dietTypes: ["omnivore", "vegetarian"],
    allergySafe: [],
    allergyRisk: ["gluten", "soy"],
    healthGoals: [],
  },
  {
    id: "5",
    name: "Dunkin Donuts",
    type: "American Cafe",
    image: require("../assets/images/dunkin.jpg"),
    route: "/restaurantprof_dunkin",
    latitude: 28.6068,
    longitude: -81.1986,
    rating: 2.8,
    price: 1,
    hours: [
      "Monday: 6:00 AM – 8:00 PM",
      "Tuesday: 6:00 AM – 8:00 PM",
      "Wednesday: 6:00 AM – 8:00 PM",
      "Thursday: 6:00 AM – 8:00 PM",
      "Friday: 6:00 AM – 8:00 PM",
      "Saturday: 7:00 AM – 8:00 PM",
      "Sunday: 7:00 AM – 5:00 PM",
    ],
    dietTypes: ["omnivore", "vegetarian"],
    allergySafe: [],
    allergyRisk: ["dairy", "gluten", "eggs"],
    healthGoals: ["lowsugar"],
  },
  {
    id: "6",
    name: "Purple Ocean Superfood Bar",
    type: "Vegan Kitchen",
    image: require("../assets/images/purple.jpg"),
    route: "/restaurantprof_purple",
    latitude: 28.6020,
    longitude: -81.2007,
    rating: 3.5,
    price: 2,
    hours: [
      "Monday: 9:00 AM – 6:00 PM",
      "Tuesday: 9:00 AM – 6:00 PM",
      "Wednesday: 9:00 AM – 6:00 PM",
      "Thursday: 9:00 AM – 6:00 PM",
      "Friday: 9:00 AM – 6:00 PM",
      "Saturday: Closed",
      "Sunday: Closed",
    ],
    dietTypes: ["vegan", "vegetarian", "pescatarian"],
    allergySafe: ["gluten", "dairy", "eggs", "soy"],
    allergyRisk: [],
    healthGoals: ["manageweight", "lowfat", "lowsugar"],
  },
  {
    id: "7",
    name: "Starbucks",
    type: "Coffee & Drinks",
    image: require("../assets/images/starbucks.webp"),
    route: "/restaurantprof_starbucks",
    latitude: 28.6033,
    longitude: -81.1989,
    rating: 3.8,
    price: 2,
    hours: [
      "Monday: 7:30 AM – 5:00 PM",
      "Tuesday: 7:30 AM – 5:00 PM",
      "Wednesday: 7:30 AM – 5:00 PM",
      "Thursday: 7:30 AM – 5:00 PM",
      "Friday: 7:30 AM – 4:00 PM",
      "Saturday: Closed",
      "Sunday: Closed",
    ],
    dietTypes: ["omnivore", "vegetarian", "vegan"],
    allergySafe: [],
    allergyRisk: ["dairy"],
    healthGoals: ["lowsugar"],
  },
  {
    id: "8",
    name: "Halal Shack",
    type: "Halal food",
    image: require("../assets/images/thehalal.png"),
    route: "/restaurantprof_halal",
    latitude: 28.6016,
    longitude: -81.2013,
    rating: 3.7,
    price: 1,
    hours: [
      "Monday: 11:00 AM – 8:00 PM",
      "Tuesday: 11:00 AM – 8:00 PM",
      "Wednesday: 11:00 AM – 8:00 PM",
      "Thursday: 11:00 AM – 8:00 PM",
      "Friday: 11:00 AM – 6:00 PM",
      "Saturday: Closed",
      "Sunday: Closed",
    ],
    dietTypes: ["omnivore"],
    allergySafe: [],
    allergyRisk: ["gluten"],
    healthGoals: ["manageweight"],
  },
  {
    id: "9",
    name: "Einstein Bros. Bagels",
    type: "Cafe & Bakery",
    image: require("../assets/images/einsteinbros.jpeg"),
    route: "/restaurantprof_einstein",
    latitude: 28.6009,
    longitude: -81.1993,
    rating: 3.1,
    price: 1,
    hours: [
      "Monday: Closed",
      "Tuesday: 9:00 AM – 4:00 PM",
      "Wednesday: 9:00 AM – 4:00 PM",
      "Thursday: 9:00 AM – 4:00 PM",
      "Friday: 9:00 AM – 4:00 PM",
      "Saturday: Closed",
      "Sunday: Closed",
    ],
    dietTypes: ["omnivore", "vegetarian"],
    allergySafe: [],
    allergyRisk: ["gluten", "dairy", "eggs", "wheat"],
    healthGoals: [],
  },
  {
    id: "10",
    name: "Bento Asian Kitchen",
    type: "Asian Fusion",
    image: require("../assets/images/bentoasian.jpeg"),
    route: "/restaurantprof_bento",
    latitude: 28.6018,
    longitude: -81.2010,
    rating: 3.1,
    price: 1,
    hours: [
      "Monday: 11:00 AM – 8:00 PM",
      "Tuesday: 11:00 AM – 8:00 PM",
      "Wednesday: 11:00 AM – 8:00 PM",
      "Thursday: 11:00 AM – 8:00 PM",
      "Friday: 11:00 AM – 8:00 PM",
      "Saturday: 11:00 AM – 6:00 PM",
      "Sunday: 11:00 AM – 6:00 PM",
    ],
    dietTypes: ["omnivore", "vegetarian", "pescatarian"],
    allergySafe: [],
    allergyRisk: ["soy", "fish", "gluten"],
    healthGoals: [],
  },
];